apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  type: LoadBalancer # to get an external IP as it is an entry point
  selector:
    app: gateway
  ports:
  - port: 80 # default port for the entry point
    targetPort: 9696 # containerPod in gateway_deployment.yaml
