# model deployment file for kubernetes
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tf-serving-clothing-model
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tf-serving-clothing-model
  template:
    metadata:
      labels:
        app: tf-serving-clothing-model
    spec:
      containers:
      - name: tf-serving-clothing-model
        image: clothing-model:xception-v4-001 # model image
        resources:
          limits:
            memory: "512Mi" # 512 Mb of memory to operate the model
            cpu: "1" # can take all cpu
        ports:
        - containerPort: 8500